In [7]:
# Looping over arrays in python (slower) 
import numpy as np 
arr=np.array([1,2,3,4,5])
result=[]
for i in arr:
    result.append(i**2)
result=np.array(result)
print(result)

[ 1  4  9 16 25]


In [11]:
#Vectorizating function (faster)
result_vect=arr**2
print(result_vect)

[ 1  4  9 16 25]


In [12]:
# Broadcasting 
result_vect+10

array([11, 14, 19, 26, 35])

In [14]:
 #Broadcasting a 2D Array and a 1D Array
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])
result=arr1+arr2
result

array([[2, 4, 6],
       [5, 7, 9]])

# How Broadcasting Works
1. Dimensions must be compatible: The size of the trailing dimensions of the arrays must be either the same or one of them must be 1.
2. Stretching arrays: If the shapes are compatible, NumPy stretches the smaller array to match the larger one, element-wise, without copying data.

# Hands-on: Applying Broadcasting to Real-World Scenarios
Let’s apply broadcasting to a real-world scenario: scaling data in machine learning.

## Example: Normalizing Data Using Broadcasting
Imagine you have a dataset where each row represents a sample and each column represents a feature. You can normalize the data by subtracting the mean of each column and dividing by the standard deviation.

In [25]:
data=np.array([[10,20,30],
               [15,25,35],
               [20,30,40],
               [25,35,45],
               [30,40,50]])

mean=data.mean(axis=0)
std=data.std(axis=0)
normalized_data=(data-mean)/std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
