In [1]:
import numpy as np 


In [2]:
!pip install numpy 

### Creating NumPy Arrays

In [27]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

### Creating Arrays from Scratch

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [7]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [11]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Checking Array Properties

In [12]:
myarr.shape

(4, 3)

In [13]:
myarr.size

12

In [14]:
myarr.ndim

2

In [15]:
myarr.dtype

dtype('int64')

### Changing Data Types

In [16]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float32')

In [17]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [18]:
myarr.dtype

dtype('float32')

In [19]:
n=myarr.astype('float64')

In [20]:
n.dtype

dtype('float64')

In [21]:
myarr.dtype

dtype('float32')

In [22]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr.shape

(4, 3)

In [23]:
reshape=myarr.reshape((3,4))

In [24]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
reshape2=myarr.reshape((6,2))
reshape2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [26]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])