In [1]:
import numpy as np 

In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [50]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
flat_arr=arr.flatten()

In [52]:
flat_arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat_arr[0]

np.int64(1)

In [20]:
flat_arr=flat_arr.astype('int')

In [22]:
int(flat_arr[1])

2

In [23]:
flat_arr[3:6]

array([4, 5, 6])

In [24]:
flat_arr[:5]  # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [25]:
flat_arr[3:] #same as flat[3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
flat_arr[3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
flat_arr[::2] # every second element 

array([ 1,  3,  5,  7,  9, 11])

In [53]:
flat_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
b=flat_arr[3:7].copy() # This is not slice because we are using copy method to get the copy 

In [55]:
b

array([4, 5, 6, 7])

In [56]:
b[0]=4444444

In [57]:
b

array([4444444,       5,       6,       7])

In [58]:
flat_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
 arr=np.array([1,54,23,53,2,3,34,5,6])

In [64]:
arr

array([ 1, 54, 23, 53,  2,  3, 34,  5,  6])

In [65]:
arr[[1,4,6]]

array([54,  2, 34])

In [67]:
arr[arr>23]

array([54, 53, 34])

# Exercises for Practice
- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats [1.1, 2.2, 3.3] into integers.
- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
- Reshape a 1D array of size 9 into a 3×3 matrix.
- Use boolean masking to filter numbers greater than 50 in an array.

In [132]:
#Create a 3×3 array filled with random numbers and print its shape.
# import random
# mat=[]
# for i in range(1,4):
#     mat1=[]
#     for j in range (1,4):
#         mat1.append(random.random())
#     mat.append(mat1)
# mat_arr=np.array(mat)
# mat
# mat_arr.shape

# best cleanest Numpy sol 
mat_arr1 = np.random.random((3, 3))
print(mat_arr1)
print(mat_arr1.shape)




[[0.39081399 0.78050472 0.64645979]
 [0.77004725 0.06639847 0.32052012]
 [0.06001636 0.51927601 0.54483086]]
(3, 3)


In [134]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr_float=np.array([1.1, 2.2, 3.3])
arr_float.dtype
arr_int=arr_float.astype(int) 
arr_int

array([1, 2, 3])

In [124]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr_no = np.arange(1,11,1)
idx=np.where(arr_no%2==0)[0]
even_arr=arr_no[idx]
even_arr

array([ 2,  4,  6,  8, 10])

In [116]:
# Reshape a 1D array of size 9 into a 3×3 matrix.
arr=np.arange(1,10,1)
reshaped_arr=arr.reshape((3,3))
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
#Use boolean masking to filter numbers greater than 50 in an array.

bol_arr=np.arange(1,100,8)
bol_arr[bol_arr>50]

array([57, 65, 73, 81, 89, 97])