# Built in Mathematical functions in Numpy
Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

1. **`np.mean()`** – Compute the **mean** (average) of an array.
   ```python
   np.mean(arr)
   ```

2. **`np.std()`** – Compute the **standard deviation** of an array.
   ```python
   np.std(arr)
   ```

3. **`np.var()`** – Compute the **variance** of an array.
   ```python
   np.var(arr)
   ```

4. **`np.min()`** – Compute the **minimum** value of an array.
   ```python
   np.min(arr)
   ```

5. **`np.max()`** – Compute the **maximum** value of an array.
   ```python
   np.max(arr)
   ```

6. **`np.sum()`** – Compute the **sum** of all elements in an array.
   ```python
   np.sum(arr)
   ```

7. **`np.prod()`** – Compute the **product** of all elements in an array.
   ```python
   np.prod(arr)
   ```

8. **`np.median()`** – Compute the **median** of an array.
   ```python
   np.median(arr)
   ```

9. **`np.percentile()`** – Compute the **percentile** of an array.
   ```python
   np.percentile(arr, 50)  # For the 50th percentile (median)
   ```

10. **`np.argmin()`** – Return the **index of the minimum** value in an array.
    ```python
    np.argmin(arr)
    ```

11. **`np.argmax()`** – Return the **index of the maximum** value in an array.
    ```python
    np.argmax(arr)
    ```

12. **`np.corrcoef()`** – Compute the **correlation coefficient** matrix of two arrays.
    ```python
    np.corrcoef(arr1, arr2)
    ```

13. **`np.unique()`** – Find the **unique elements** of an array.
    ```python
    np.unique(arr)
    ```

14. **`np.diff()`** – Compute the **n-th differences** of an array.
    ```python
    np.diff(arr)
    ```

15. **`np.cumsum()`** – Compute the **cumulative sum** of an array.
    ```python
    np.cumsum(arr)
    ```

16. **`np.linspace()`** – Create an array with **evenly spaced numbers** over a specified interval.
    ```python
    np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
    ```

17. **`np.log()`** – Compute the **natural logarithm** of an array.
    ```python
    np.log(arr)
    ```

18. **`np.exp()`** – Compute the **exponential** of an array.
    ```python
    np.exp(arr)
    ```

These methods are used for performing mathematical and statistical operations with NumPy# Built in Mathematical functions in Numpy
Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

1. **`np.mean()`** – Compute the **mean** (average) of an array.
   ```python
   np.mean(arr)
   ```

2. **`np.std()`** – Compute the **standard deviation** of an array.
   ```python
   np.std(arr)
   ```

3. **`np.var()`** – Compute the **variance** of an array.
   ```python
   np.var(arr)
   ```

4. **`np.min()`** – Compute the **minimum** value of an array.
   ```python
   np.min(arr)
   ```

5. **`np.max()`** – Compute the **maximum** value of an array.
   ```python
   np.max(arr)
   ```

6. **`np.sum()`** – Compute the **sum** of all elements in an array.
   ```python
   np.sum(arr)
   ```

7. **`np.prod()`** – Compute the **product** of all elements in an array.
   ```python
   np.prod(arr)
   ```

8. **`np.median()`** – Compute the **median** of an array.
   ```python
   np.median(arr)
   ```

9. **`np.percentile()`** – Compute the **percentile** of an array.
   ```python
   np.percentile(arr, 50)  # For the 50th percentile (median)
   ```

10. **`np.argmin()`** – Return the **index of the minimum** value in an array.
    ```python
    np.argmin(arr)
    ```

11. **`np.argmax()`** – Return the **index of the maximum** value in an array.
    ```python
    np.argmax(arr)
    ```

12. **`np.corrcoef()`** – Compute the **correlation coefficient** matrix of two arrays.
    ```python
    np.corrcoef(arr1, arr2)
    ```

13. **`np.unique()`** – Find the **unique elements** of an array.
    ```python
    np.unique(arr)
    ```

14. **`np.diff()`** – Compute the **n-th differences** of an array.
    ```python
    np.diff(arr)
    ```

15. **`np.cumsum()`** – Compute the **cumulative sum** of an array.
    ```python
    np.cumsum(arr)
    ```

16. **`np.linspace()`** – Create an array with **evenly spaced numbers** over a specified interval.
    ```python
    np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
    ```

17. **`np.log()`** – Compute the **natural logarithm** of an array.
    ```python
    np.log(arr)
    ```

18. **`np.exp()`** – Compute the **exponential** of an array.
    ```python
    np.exp(arr)
    ```

These methods are used for performing mathematical and statistical operations with NumPy

In [4]:
import numpy as np 
arr=np.array([3,5,2,33])
print(np.mean(arr))

10.75


In [9]:
print(np.min(arr))
print(np.max(arr))


2
33


In [10]:
print(np.std(arr))
print(np.var(arr))

12.891373084353738
166.1875


In [11]:
print(np.sum(arr))
print(np.prod(arr))

43
990


In [14]:
print(np.median(arr))
print(np.percentile(arr,50))

4.0
4.0


In [15]:
print(np.argmin(arr))
print(np.argmax(arr))

2
3


In [17]:
arr2=np.array([1,2,3,4])
print(np.corrcoef(arr,arr2))

[[1.         0.75452752]
 [0.75452752 1.        ]]


In [19]:
arr=np.array([3,5,2,33,2,5,3,33])
print(np.unique(arr))

[ 2  3  5 33]


In [20]:
arr=np.array([3,5,2,33])
print(np.diff(arr))

[ 2 -3 31]


In [21]:
print(np.cumsum(arr))

[ 3  8 10 43]


In [23]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [25]:
print(np.log(arr))
print(np.exp(arr))


[1.09861229 1.60943791 0.69314718 3.49650756]
[2.00855369e+01 1.48413159e+02 7.38905610e+00 2.14643580e+14]
