# Multidimensional Indexing and Axis
NumPy allows you to efficiently work with multidimensional arrays, where indexing and axis manipulation play a crucial role. Understanding how indexing works across multiple dimensions is essential for data science and machine learning tasks.

## 1. Understanding Axes in NumPy
Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:

1D array → 1 axis (axis 0)
2D array → 2 axes (axis 0 = rows, axis 1 = columns)
3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)
Example: Axes in a 2D Array

In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
print(np.sum(arr,axis=0))

[12 15 18]


In [3]:
print(np.sum(arr,axis=1))


[ 6 15 24]


## 2. Indexing in Multidimensional Arrays
You can access elements using row and column indices.


In [5]:
int(arr[0][1])

2

In [6]:
int(arr[0,1]) #0 row 1 col

np.int64(2)

In [11]:
arr[0:2,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

## 3. Indexing in 3D Arrays
For 3D arrays, the first index refers to the "depth" (sheets of data).

In [30]:
arr3d=np.array([
    [[1,2,3],
     [4,5,6]],
                [[7,8,9],
                 [10,11,12]]
])


In [33]:
print(arr3d[:,0,:])

[[1 2 3]
 [7 8 9]]


In [36]:
# first col from 2d and 3d array
first_col=arr3d[:,:,0]
print(first_col)
firstcol_2d=arr[:,0]
print(firstcol_2d)

[[ 1  4]
 [ 7 10]]
[1 4 7]


In [40]:
# first row from 2d and 3d array
print(arr[0,:])
print(arr3d[:,0,:])

[1 2 3]
[[1 2 3]
 [7 8 9]]


## 5. Changing Data Along an Axis

In [46]:
# Replace all elements in column 1 with 0
arr[:,0]=0
print(arr)
arr3d[:,:,0]=0
print("\n",arr3d)

[[0 2 3]
 [0 5 6]
 [0 8 9]]

 [[[ 0  2  3]
  [ 0  5  6]]

 [[ 0  8  9]
  [ 0 11 12]]]


### 6. Summary
- Axis 0 = rows (vertical movement), Axis 1 = columns (horizontal movement)
- Indexing works as arr[row, column] for 2D arrays and arr[depth, row, column] for 3D arrays
- Slicing allows extracting subarrays
- Operations along axes help efficiently manipulate data without loops