# Data Types in NumPy
Let's learn about NumPy’s data types and explore how they affect memory usage and performance in your arrays.

## 1. Introduction to NumPy Data Types
NumPy arrays are homogeneous, meaning that they can only store elements of the same type. This is different from Python lists, which can hold mixed data types. NumPy supports various data types (also called dtypes), and understanding them is crucial for optimizing memory usage and performance.

### Common Data Types in NumPy:
- `int32`, `int64`: Integer types with different bit sizes.
- `float32`, `float64`: Floating-point types with different precision.
- `bool`: Boolean data type.
- `complex64`, `complex128`: Complex number types.
- `object`: For storing objects (e.g., Python objects, strings).

You can check the dtype of a NumPy array using the `.dtype` attribute.

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr.dtype

dtype('int64')

## 2.Changing Data Types
You can cast (convert) the data type of an array using the `.astype()` method. This is useful when you need to change the type for a specific operation or when you want to reduce memory usage.

In [16]:
# Convert it into float 32 
np.astype(arr,"int32")

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [17]:
arr2=np.array([1,2,3,4,5],'float32')

In [18]:
arr2.dtype

dtype('float32')

### Example: Downcasting to Save Memory


In [23]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

[1000000 2000000 3000000]
int32


## 3. Why Data Types Matter in NumPy
The choice of data type affects:

- Memory Usage: Smaller data types use less memory.
- Performance: Operations on smaller data types are faster due to less data being processed.
- Precision: Choosing the appropriate data type ensures that you don't lose precision (e.g., using `float32` instead of `float64` if you don't need that extra precision).

In [19]:
arr2

array([1., 2., 3., 4., 5.], dtype=float32)

In [20]:
arr2.nbytes

20

In [21]:
arr.nbytes

48

In [22]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


## 4. String Data Type in NumPy
Although NumPy arrays typically store numerical data, you can also store strings by using the `dtype='str'` or `dtype='U'` (Unicode string) format. However, working with strings in NumPy is less efficient than using lists or Python's built-in string types

In [29]:
arr=np.array(['apple','banana','cherry'],'U10')
arr

array(['apple', 'banana', 'cherry'], dtype='<U10')

## 5. Complex Numbers
NumPy also supports complex numbers, which consist of a real and imaginary part. You can store complex numbers using `complex64` or `complex128` data types.

In [34]:
arr=np.array([1+2j,3+4j,5+6j],dtype='complex64')
print(arr[0]+arr[1])

(4+6j)


## 6. Object Data Type
If you need to store mixed or complex data types (e.g., Python objects), you can use `dtype='object'`. However, this type sacrifices performance, so it should only be used when absolutely necessary.

In [37]:
arr=np.array([{'a':1},[1,2,3,4],'hello'],dtype='object')
print(arr)
arr.dtype

[{'a': 1} list([1, 2, 3, 4]) 'hello']


dtype('O')