In [5]:
#Python Zip Explaination 
#l1=[1,2,3,4
#l2=[5,6,7,8]
#list(zip(l1,l2))

In [3]:
#using python list
import time 
size=1_000_000_0
l1=list(range(size))
l2=list(range(size))
start=time.time()
add=[x+y for x,y in zip(l1,l2)]
end=time.time()
print(add[0:20])
print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
1.6924102306365967


In [4]:
#using numpy arrays
import numpy as np 
size=1_000_000_0
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))
start=time.time()
add=l1+l2
end=time.time()
print(add[0:20])
print(end-start)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
0.4958360195159912


In [9]:
np.array([1,2,3,4,5]) 

array([1, 2, 3, 4, 5])

In [15]:
arr=np.array([[1,2,3],[4,5,6]]) 
#np.array([[1,2,3],[4,5,6,7,8,9]]) will throw error

In [16]:
type(arr)


numpy.ndarray

In [17]:
arr.shape

(2, 3)

### Memory efficency list vs numpy array 

In [23]:
import sys 
list_data=list(range(1000))
numpy_arr=np.array(list(range(size)))
print("Python list size is:" ,sys.getsizeof(list_data)*len(list_data),"bytes")
print("Numpy array size is:" ,numpy_arr.nbytes,"bytes")

Python list size is: 8056000 bytes
Numpy array size is: 80000000 bytes


### Vectorization (No more loops!) 


In [37]:
size=1000
list1=list(range(size))
start=time.time()
sq=[x ** 2 for x in list1]
end=time.time()
print(end-start) 


0.0013222694396972656


In [39]:
np_arr=np.array(list1)
start=time.time()
sq_arr=np_arr**2
end=time.time()
print(end-start) 


0.00035262107849121094


# Exercises for Practice
- Create a NumPy array with values from 10 to 100 and print its shape.
- Compare the time taken to multiply two Python lists vs. two NumPy arrays.
- Find the memory size of a NumPy array with 1 million elements.

In [52]:
#Create a NumPy array with values from 10 to 100 and print its shape.
# list1=[]
# for x in range(10,101):
#            list1.append(x)
# numpy_arr=np.array(list1)
# numpy_arr.shape

numpy_arr = np.arange(10, 101)   
print(numpy_arr)
print(numpy_arr.shape)


[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
(91,)


In [74]:
#Compare the time taken to multiply two Python lists vs. two NumPy arrays.
list1=[x for x in range(1,6)]
list2=[x for x in range(6,11)]
start=time.time()
mul_list=[x*y for x,y in zip(list1,list2)]
end=time.time()
print(mul_list,"time:",end-start)
arr1=np.array(list1)
arr2=np.array(list2)
start1=time.time()
mul_arr=arr1*arr2
end1=time.time()
print(mul_arr,"time:",end1-start1)

[6, 14, 24, 36, 50] time: 0.0001926422119140625
[ 6 14 24 36 50] time: 0.000110626220703125


In [75]:
#Find the memory size of a NumPy array with 1 million elements.
size=1_000_000
arr=np.array(list(range(size)))
print(arr.nbytes,"bytes")

8000000 bytes
